language: node_js
node_js:
  - node

cache: npm

install:
  - npm install

script:
  - npm run build

deploy:
  provider: s3
  bucket: "xn--90aexm.xn--80aaatyni4c.xn--p1ai"
  skip_cleanup: true
  local_dir: dist
  region: eu-central-1
