language: node_js
node_js:
  - node

cache: npm

install:
  - npm install

script:
  - npm run build

deploy:
  provider: s3
  bucket: "xn--80a0abxb.xn--80aaatyni4c.xn--p1ai"
  skip_cleanup: true
  local_dir: dist
  endpoint: "https://storage.yandexcloud.net"
